const name = 'giorgi';
console.log(name);
const dayOfWeek = 'monday';
console.log(dayOfWeek);
const favoriteActivity = 'coding';
console.log(favoriteActivity);
const userAge = 25;
console.log(userAge);
const userisStudent = true;
console.log(userisStudent);
let notdefined;
console.log(notdefined);
const emptyValue = null;
console.log(emptyValue);
const message = "Hi my name is" + " " + name;
console.log(message);
const message2 = "Today is" + " " + dayOfWeek;
console.log(message2);
const message3 = "a perfect day for" + " " + favoriteActivity;
console.log(message3);
const message4 = "I am" + " " + userAge + " " + "years old";
console.log(message4);